# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Open-loop session-arrival configuration for the AGENTIC_REPLAY timing mode."""

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, Field

from aiperf.config.base import BaseConfig
from aiperf.plugin.enums import ArrivalPattern


class SessionArrivalConfig(BaseConfig):
    """Exogenous session-arrival process for agentic trace replay.

    Presence of this section switches the profiling phase from the default
    CLOSED loop (a fixed set of ``concurrency`` trajectory lanes, each recycling
    into a fresh trace the moment its tree drains) to an OPEN loop: session
    starts are generated by an arrival process and are independent of
    completions, so the in-system session count is a consequence of the rate and
    the per-session residence time rather than a configured constant.

    Only session STARTS are metered. Main-turn continuations, subagent fan-out
    groups and subagent inner turns keep their recorded causal timing and are
    never thinned by this rate.
    """

    model_config = ConfigDict(extra="forbid")

    rate: Annotated[
        float,
        Field(
            gt=0,
            description="Exogenous session-arrival rate in sessions per second. "
            "Each arrival replays a trace from turn 0 with its own cache-bust "
            "marker and X-Session-ID salt. ``concurrency`` becomes an admission "
            "ceiling (arrivals above it are rejected and counted, not queued); "
            "leave it unset for an uncapped open loop. No t* snapshot warmup "
            "phase is synthesized in this mode.",
        ),
    ]

    pattern: Annotated[
        ArrivalPattern,
        Field(
            default=ArrivalPattern.POISSON,
            description="Inter-arrival distribution. 'poisson' (default) gives "
            "exponential inter-arrival times, 'constant' gives a fixed period, "
            "'gamma' adds tunable burstiness via ``smoothness``.",
        ),
    ]

    smoothness: Annotated[
        float | None,
        Field(
            default=None,
            gt=0,
            description="Gamma shape parameter. 1.0 is Poisson-equivalent, <1.0 "
            "is burstier (clustered session starts), >1.0 is more regular. Only "
            "used when ``pattern`` is 'gamma'.",
        ),
    ]
